# This file was generated by GoReleaser. DO NOT EDIT.
class Deduplicater < Formula
  desc "Find and manage duplicate files."
  homepage "https://github.com/driessamyn/deduplicater"
  version "0.1.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/driessamyn/deduplicater/releases/download/v0.1.1/deduplicater_0.1.1_darwin_amd64.tar.gz"
    sha256 "c10daabcd208f428be84d70a75b7348f7a94e888ba44283973d9f56ee0b60195"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/driessamyn/deduplicater/releases/download/v0.1.1/deduplicater_0.1.1_linux_amd64.tar.gz"
    sha256 "65bcd4016e6c725f79bf8a70b3d30b6b1b2632b91162918f056bc80e109bc530"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/driessamyn/deduplicater/releases/download/v0.1.1/deduplicater_0.1.1_linux_arm64.tar.gz"
    sha256 "0a813133be57e91cbb5c82c3f8508510b378ef05b1fe2816961bb8f6af52578a"
  end

  def install
    bin.install "deduplicater"
  end
end
